services:
  postgres:
    image: postgres:17.5
    container_name: postgres-container
    environment:
      POSTGRES_USER: SYSDBA
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: authorization
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      itsql_network:
        ipv4_address: 172.52.52.10

volumes:
  postgres_data:
networks:
  itsql_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.52.52.0/24
